# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m

linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  nolintlint:
    package-comments: false

linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
  exclude:
    - package comment should be of the form 